server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.176.131/12306?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl